name: Telegram web app/Template 1 build and deploy

on:
  push:
    branches:
      - master
    paths:
      - src/LionCbdShop.TelegramWebApp.Template1/**
  workflow_dispatch:

env:
  APP_LOCATION: "src/LionCbdShop.TelegramWebApp.Template1/"
  APP_BUILD_LOCATION: "build"
  ARTIFACT_NAME: "TelegramWebAppTemplate1"

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    defaults:
      run:
        working-directory: ${{ env.APP_LOCATION }}
      
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Build
        run: | 
          npm install
          npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ format('{0}/{1}/{2}', github.workspace, env.APP_LOCATION, env.APP_BUILD_LOCATION) }}
      
