name: Telegram web app/Template 1 build and deploy

on:
  push:
    branches:
      - master
    paths:
      - src/LionCbdShop.TelegramWebApp.Template1/**
  workflow_dispatch:

env:
  APP_LOCATION: "src/LionCbdShop.TelegramWebApp.Template1/"
  APP_BUILD_LOCATION: "build"
  ARTIFACTS_NAME: "TelegramWebAppTemplate1"

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
      
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Install npm dependencies
        run: npm install
      - name: Build project
        run: npm run build --prefix src/LionCbdShop.TelegramWebApp.Template1
      - name: Archive build artifacts
        run: tar -zcvf build-artifacts.tar.gz build
        env:
          ARTIFACTS_NAME: build-artifacts.tar.gz
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          path: build-artifacts.tar.gz
      
  DeployToDev:
    runs-on: ubuntu-latest
    name: Deploy to Development
    needs: [Build]
    environment:
      name: Development
    
    steps: 
      - name: Download a Build Artifact
        id: downloadbuildartifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ env.ARTIFACTS_NAME }}
      - name: Deploy to azure static web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: ${{ steps.downloadbuildartifact.outputs.download-path }}
          azure_static_web_apps_api_token: ${{ secrets.TELEGRAM_WEB_APP_TEMPLATE_1_DEPLOYMENT_SECRET }}
