name: Telegram web app/Template 1 CI/CD 

on:
  push:
    branches:
      - master
    paths:
      - src/LionCbdShop.TelegramWebApp.Template1/**

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "src/LionCbdShop.TelegramWebApp.Template1/" # location of your client code
  APP_ARTIFACT_LOCATION: "src/LionCbdShop.TelegramWebApp.Template1/build" # location of client code build output

defaults:
 run:
  working-directory: "${{ env.APP_LOCATION }}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build app
        run: npm run build
      - name: Azure Static Web Apps Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.TELEGRAM_WEB_APP_TEMPLATE_1_DEPLOYMENT_SECRET }}
          action: "upload"
          app_location: "${{ env.APP_LOCATION }}" # App source code path
          output_location: "${{ env.APP_ARTIFACT_LOCATION }}" # Built app content directory - optional
